src/Services/FilesService.php
Added possibility for retrieving file info by given Id.
=> [ADD-531] Added method for retrieving file info.

src/Entities/Addons/AddonFile.php, src/Services/AddonFileService.php, src/Services/AddonsService.php, src/Services/FilesService.php
- Added: addon files get endpoint
- Removed: files get endpoint
=> [ADD-531] Added addon-files get endpoint.

src/Services/TemplatesService.php
- Added method for retrieving template documents
=> [ADD-476] Return template documents fields.

src/Http/Client.php
- Reset filters after request was made
=> Fixed filters reset.

src/Services/AddonFileService.php
- Added `download` method for AddonFiles
Depends on https://github.com/airslateinc/addons-api/pull/191
=> [ADD-785] Added method for addon file download.

src/Models/Template/TemplateDocument.php, src/Services/TemplatesService.php
Now it is possible to attach document via TemplateService::addDocument(), passing into slate id, template id and TemplateDocument DTO.
=> [AS-897] added new resource into public client

src/Services/PacketsService.php
* Added method for sending slate
=> Added method for sending slate

src/Services/PacketsService.php
- Added packet send revoke.
Depends on https://github.com/airslateinc/slates-api/pull/302
=> [ADD-1193] Added packet send revoke

src/Entities/SlateInvite.php, src/Services/SlatesService.php
=> [ADD-951] Add SlateInvite entity

src/Services/PacketsService.php
* Changed send slate request method
=> Fix send slate request method

src/Services/DocumentsService.php
- Fix updateFields response type
=> [ADD-1032] Fix updateFields response

src/Entities/Packets/RevisionLinks.php, src/Services/PacketsService.php, src/Services/RevisionsService.php
Changelog:
- added endpoint to retrieve packet revision link
=> [ADD-1468] add revision service

src/Client.php, src/Entities/Packets/RevisionDocument.php, src/Models/RevisionDocument/BulkUpdate.php, src/Services/RevisionsService.php
Adding support of revision documents:
- get revision documents
- bulk update of revision documents
=> ADD-1715 Revision documents

src/Client.php, src/Services/AddonsSmsService.php
=> [ADD-1786] Add addons sms endpoint

src/Services/PacketsService.php
1. Add delete packet
Depends on: [https://github.com/airslateinc/slates-api/pull/454](https://github.com/airslateinc/slates-api/pull/454)
=> [ADD-2031] Add delete packet

composer.json, src/Entities/BaseEntity.php, tests/Unit/Entities/BaseEntityTest.php, tests/Unit/fixtures/documents/document.json, tests/Unit/fixtures/documents/documents_collection.json
- Set includes based on entity relations.
=> [ADD-2095] Set includes based on entity relations.

src/Client.php, src/Entities/PacketRevision.php, src/Services/PacketRevisionsService.php
1. Added packet-revisions endpoint
=> Added packet-revisions endpoint

src/Entities/Packets/Revision.php, src/Services/RevisionsService.php
1.  Add endpoint get packet revisions.
=> [ADD-1652] Add endpoint get packet revisions

src/Models/Revision/Create.php, src/Services/RevisionsService.php
1. Add create packet revision.
=> [ADD-2238] Add create packet revision

src/Models/Packet/Update.php, src/Services/PacketsService.php
=> [ADD-2377] Add update packet

src/Services/AddonIntegrationsService.php
Depends on https://github.com/airslateinc/addons-api/pull/448
=> [ADD-2553] Renamed endpoints addons/integrations to addons-integrations.

src/Entities/DocumentPermissions.php, src/Entities/DocumentPermissions/CustomBooleanOption.php, src/Entities/DocumentPermissions/CustomOptions.php, src/Entities/DocumentPermissions/EnableComments.php, src/Entities/DocumentPermissions/EnableToolbar.php
- Added custom options to DocumentPermissions.
Depends on https://github.com/airslateinc/documents-api/pull/348
=> [ADD-2739] Added custom options to DocumentPermissions entity.

src/Entities/DocumentPermissions.php
=> Added fallback for CustomOptions.

src/Models/Document/DocumentEvent.php, src/Services/DocumentsService.php
https://pdffiller.atlassian.net/browse/ADD-2015
=> Add 2015 add document events to client

src/Entities/BaseEntity.php
=> [ADD-1652] Fix get includes

src/Entities/BaseEntity.php
1. Return old method work prepareIncludes and add original included.
=> [ADD-1652] Return old method work prepareIncludes and add original included

src/Entities/EntityType.php, src/Entities/Field.php, src/Exceptions/Packets/NoSuchUserException.php, src/Exceptions/Packets/UserHasNoAccessException.php, src/Services/PacketsService.php
Added a method for checking the access to the revision via email
=> [ADD-2892] check revision access endpoint

src/Client.php
https://pdffiller.atlassian.net/browse/JSF-5953
=> [JSF-5953] fixed timeout config

src/Entities/EntityType.php, src/Models/Packet/Send/Create.php, src/Services/PacketsService.php
=> [ADD-2325] Invite email additions

src/Entities/PacketRevision.php, src/Services/PacketRevisionsService.php, src/Services/PacketsService.php
Used to move export to public slates API instead of internal API
=> Get packet revision method added

src/Services/PacketsService.php
Response https://pdffiller.slack.com/files/U50G9NP9R/FJQA0CRL0/respons.php
=> [Fix] fixed return value from "/v1/slates/.../packets/.../send" endpoint

src/Models/Packet/InviteEmailAddition.php, src/Models/Packet/Send/Bulk.php
Blocked https://github.com/airslateinc/slates-api/pull/1155
=> [SAL-4953] send a slate bulk - added custom title and preheader

src/Models/Packet/SigningOrder/Enable.php
Add the possibility to pass the custom preheader and title in the send a slate with roles message
=> [AAD-491] Add the possibility to pass the custom preheader and title

src/Models/Document/Create.php
=> [ARCH-1202] Document.create - remove default values/sections from toArray

src/Client.php
Added headers:
- Content-Type: application/vnd.api+json
- Accept: application/json, application/vnd.api+json
=> [ABC-1713] Adding content-type and accept headers

src/Services/AddonsService.php
- SlateAddonIntegrationsService to AddonsService added
=> SlateAddonIntegrationsService to AddonsService added

src/Models/Packet/UnassignRole.php
Change the toArray method of the UnassignRole entity to match the JSON API standard
=> [AAD-1698] Change the toArray method of the UnassignRole entity

src/Client.php, src/Entities/EntityType.php, src/Models/ExportZip/Create.php, src/Services/ExportZipService.php
- new export-zip endpoint added
=> [AEXT-120] export zip

src/Client.php, src/Entities/Contact.php, src/Entities/EntityType.php, src/Enums/BaseEnum.php, src/Enums/SlateInviteAccess.php, src/Exceptions/IncorrectValueForEnum.php, src/Models/SlateInvite/Create.php, src/Services/ContactService.php, src/Services/FlowsService.php
* Add request for get contacts
* Add request for create invite to flow
=> [AAD-2303] add address book & invite to flow

src/Models/Packet/Create.php
* link for task - https://pdffiller.atlassian.net/browse/AAD-2316
=> [AAD-2316]: add name attribute for create packet
